# Generated by Django 3.2.4 on 2022-10-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_token',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='forgot_password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_token',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=20),
        ),
    ]
