# Generated by Django 4.1.3 on 2022-11-06 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_department_user_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='faculty',
        ),
    ]
