# Generated by Django 4.1.3 on 2022-11-11 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salary',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
