# Generated by Django 4.1.3 on 2022-11-11 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='salary',
        ),
    ]
