# Generated by Django 3.2.4 on 2022-10-24 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_auto_20221024_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
