# Generated by Django 3.2.4 on 2022-10-27 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_auto_20221024_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam_timetable',
            name='course',
        ),
        migrations.AddField(
            model_name='exam_timetable',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.course'),
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='course',
        ),
        migrations.AddField(
            model_name='timetable',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.course'),
        ),
    ]
