# Generated by Django 3.2.4 on 2022-10-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0012_auto_20221029_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
