# Generated by Django 3.2.4 on 2022-10-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0014_rename_profilepic_student_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='time',
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profilepic.png', null=True, upload_to=''),
        ),
    ]
