# Generated by Django 3.2.4 on 2022-10-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0015_auto_20221030_0514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam_timetable',
            name='time',
        ),
        migrations.AlterField(
            model_name='exam_timetable',
            name='week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=200, null=True),
        ),
    ]
