# Generated by Django 4.1.3 on 2022-11-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0017_alter_message_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.TextField(blank=True, max_length=240, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='institution_attended',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='work_experience',
            name='staff',
        ),
        migrations.DeleteModel(
            name='File1',
        ),
        migrations.DeleteModel(
            name='Institution_Attended',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='Work_Experience',
        ),
    ]
