# Generated by Django 4.1.3 on 2022-11-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0018_status_remove_institution_attended_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profilepic.png', null=True, upload_to=''),
        ),
    ]
