# Generated by Django 4.1.3 on 2022-11-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0020_remove_lecturer_date_created_department_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
