# Generated by Django 4.1.3 on 2022-11-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0021_question_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff_Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff', models.CharField(blank=True, max_length=50, null=True)),
                ('salary', models.IntegerField(blank=True, default=0, null=True)),
                ('vat', models.IntegerField(blank=True, default=0, null=True)),
                ('trustfund', models.IntegerField(blank=True, default=0, null=True)),
                ('r_sal', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
