# Generated by Django 4.1.3 on 2022-11-11 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0022_staff_payroll_remove_course_student_course_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff_Payroll',
        ),
    ]
