# Generated by Django 4.1.3 on 2022-11-11 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0024_staff_payroll'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff_payroll',
            old_name='trustfund',
            new_name='pension',
        ),
    ]
