# Generated by Django 4.1.3 on 2022-11-11 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0025_rename_trustfund_staff_payroll_pension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_payroll',
            name='pension',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff_payroll',
            name='r_sal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff_payroll',
            name='vat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
