# Generated by Django 4.1.3 on 2022-11-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0026_alter_staff_payroll_pension_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_payroll',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
