# Generated by Django 4.1.3 on 2022-11-11 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0028_status_bg_status_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='bg',
            field=models.CharField(choices=[('success', 'green'), ('info', 'lightlue'), ('danger', 'red'), ('primary', 'blue'), ('gray', 'lightblack')], default='green', max_length=240, null=True),
        ),
    ]
