# Generated by Django 4.1.3 on 2022-11-13 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0031_register_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_course',
            name='course1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course1', to='administrator.course'),
        ),
        migrations.AddField(
            model_name='register_course',
            name='course10',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course10', to='administrator.course'),
        ),
        migrations.AddField(
            model_name='register_course',
            name='course11',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course11', to='administrator.course'),
        ),
        migrations.AddField(
            model_name='register_course',
            name='course12',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course12', to='administrator.course'),
        ),
        migrations.AddField(
            model_name='register_course',
            name='course2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course2', to='administrator.course'),
        ),
        migrations.AddField(
            model_name='register_course',
            name='course3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course3', to='administrator.course'),
        ),
        migrations.AddField(
            model_name='register_course',
            name='course4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course4', to='administrator.course'),
        ),
        migrations.AddField(
            model_name='register_course',
            name='course5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course5', to='administrator.course'),
        ),
        migrations.AddField(
            model_name='register_course',
            name='course6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course6', to='administrator.course'),
        ),
        migrations.AddField(
            model_name='register_course',
            name='course7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course7', to='administrator.course'),
        ),
        migrations.AddField(
            model_name='register_course',
            name='course8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course8', to='administrator.course'),
        ),
        migrations.AddField(
            model_name='register_course',
            name='course9',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course9', to='administrator.course'),
        ),
        migrations.AlterField(
            model_name='register_course',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='administrator.course'),
        ),
    ]
