# Generated by Django 4.1.3 on 2022-11-13 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0032_register_course_course1_register_course_course10_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_course',
            name='course_unit',
        ),
    ]
