# Generated by Django 4.1.3 on 2022-11-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0033_remove_register_course_course_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
