# Generated by Django 4.1.3 on 2022-11-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0034_course_created_by_course_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='bg',
            field=models.CharField(choices=[('success', 'green'), ('info', 'lightlue'), ('danger', 'red'), ('primary', 'blue'), ('gray', 'lightblack')], default='blue', max_length=240, null=True),
        ),
    ]
