# Generated by Django 4.1.3 on 2022-11-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0035_alter_status_bg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(blank=True, choices=[('ND1 first Semester', 'ND1 first Semester'), ('ND1 second Semester', 'ND1 second Semester'), ('ND2 first Semester', 'ND2 first Semester'), ('ND2 second Semester', 'ND2 second Semester'), ('HND1 first Semester', 'HND1 first Semester'), ('HND1 second Semester', 'HND1 second Semester'), ('HND2 first Semester', 'HND2 first Semester'), ('HND2 second Semester', 'HND2 second Semester')], default='ND1 first Semester', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='exam_timetable',
            name='week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], default='Monday', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('Option1', 'Option1'), ('Option2', 'Option2'), ('Option3', 'Option3'), ('Option4', 'Option4')], default='Option1', max_length=200),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], default='Monday', max_length=200),
        ),
    ]
