# Generated by Django 4.1.3 on 2022-11-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0037_alter_event_description_alter_event_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
