# Generated by Django 4.1.3 on 2022-11-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0038_status_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='notice',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
