# Generated by Django 4.1.3 on 2022-11-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0041_departmentnotice_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file1',
            field=models.FileField(blank=True, max_length=50, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='file2',
            field=models.FileField(blank=True, max_length=50, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='file3',
            field=models.FileField(blank=True, max_length=50, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='file4',
            field=models.FileField(blank=True, max_length=50, null=True, upload_to=''),
        ),
    ]
