# Generated by Django 4.1.3 on 2022-11-19 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0042_alter_message_file1_alter_message_file2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file3',
        ),
        migrations.RemoveField(
            model_name='message',
            name='file4',
        ),
    ]
