# Generated by Django 4.1.3 on 2022-11-19 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0043_remove_message_file3_remove_message_file4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file1',
        ),
        migrations.RemoveField(
            model_name='message',
            name='file2',
        ),
    ]
