# Generated by Django 4.1.3 on 2022-11-21 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0044_remove_message_file1_remove_message_file2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_course',
            name='course1',
        ),
        migrations.RemoveField(
            model_name='register_course',
            name='course10',
        ),
        migrations.RemoveField(
            model_name='register_course',
            name='course11',
        ),
        migrations.RemoveField(
            model_name='register_course',
            name='course12',
        ),
        migrations.RemoveField(
            model_name='register_course',
            name='course2',
        ),
        migrations.RemoveField(
            model_name='register_course',
            name='course3',
        ),
        migrations.RemoveField(
            model_name='register_course',
            name='course4',
        ),
        migrations.RemoveField(
            model_name='register_course',
            name='course5',
        ),
        migrations.RemoveField(
            model_name='register_course',
            name='course6',
        ),
        migrations.RemoveField(
            model_name='register_course',
            name='course7',
        ),
        migrations.RemoveField(
            model_name='register_course',
            name='course8',
        ),
        migrations.RemoveField(
            model_name='register_course',
            name='course9',
        ),
        migrations.AlterField(
            model_name='register_course',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.course'),
        ),
    ]
