# Generated by Django 4.1.3 on 2022-11-21 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0046_register_course_course_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='bg',
        ),
    ]
