# Generated by Django 4.1.3 on 2022-11-21 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0049_remove_result_lecturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='address_next_kin',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='name_of_next_kin',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='name_of_spouse',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='number_of_children',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='office_address',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='office_phone',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='phone_of_next_kin',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='postal_address',
        ),
    ]
