# Generated by Django 4.1.3 on 2022-11-22 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0050_remove_lecturer_address_next_kin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='other_wages',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='salary',
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.department'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.faculty'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='staff_ID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
