# Generated by Django 4.1.3 on 2022-11-23 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0051_remove_lecturer_other_wages_remove_lecturer_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='lecturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.lecturer'),
        ),
    ]
