# Generated by Django 4.1.3 on 2022-11-24 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0053_alter_timetable_lecturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='office_address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='office_phone',
        ),
    ]
