# Generated by Django 4.1.3 on 2022-11-24 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0054_remove_student_office_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='habit',
        ),
        migrations.RemoveField(
            model_name='student',
            name='hobby',
        ),
    ]
