# Generated by Django 4.1.3 on 2022-11-25 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0055_remove_student_habit_remove_student_hobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_course',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.course'),
        ),
        migrations.AlterField(
            model_name='register_course',
            name='course_unit',
            field=models.PositiveIntegerField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='register_course',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.student'),
        ),
    ]
