# Generated by Django 4.1.3 on 2022-11-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0056_alter_register_course_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_course',
            name='semester',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
