# Generated by Django 4.1.3 on 2022-11-25 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0057_alter_register_course_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_course',
            name='course_unit',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
