# Generated by Django 4.1.3 on 2022-12-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0059_alter_register_course_course_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='student',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
