# Generated by Django 4.1.3 on 2022-12-07 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0060_alter_transaction_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
    ]
