# Generated by Django 4.1.3 on 2022-12-16 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0061_remove_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='adminstatus',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
