from django.contrib import admin
from .models import *
# Register your models here.

admin.site.register(Student)
admin.site.register(Attendance)
admin.site.register(Message)
admin.site.register(Faculty)
admin.site.register(Department)
admin.site.register(Schoollevy)
admin.site.register(Lecturer)
admin.site.register(Work_Experience1)
admin.site.register(Institution_Attended1)
admin.site.register(File2)
admin.site.register(Course)
admin.site.register(Exam_Timetable)
admin.site.register(Timetable)
admin.site.register(Result)
admin.site.register(LecturerResult)
admin.site.register(Question)
admin.site.register(Result1)
admin.site.register(File)
admin.site.register(Transaction)
admin.site.register(Status)
admin.site.register(Event)
admin.site.register(Notice)
admin.site.register(Register_course)
admin.site.register(Staff_Payroll)
admin.site.register(DepartmentNotice)
