from django.urls import path, include
from .import views
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
from django.contrib.auth.views import LogoutView,LoginView
from django.contrib.auth import views as auth_views
from django.core.mail import send_mail

urlpatterns = [
    path('', views.loginsuccess, name="loginsuccess"),
    path('login_user/', views.login_user, name="login"),
    path('access/', views.access, name="access"),
    path('disapproveaccess/<str:pk>/', views.disapproveaccess, name="disapproveaccess"),
    path('approveaccess/<str:pk>/', views.approveaccess, name="approveaccess"),
    path('disapproveexamaccess/<str:pk>/', views.disapproveexamaccess, name="disapproveexamaccess"),
    path('approveexamaccess/<str:pk>/', views.approveexamaccess, name="approveexamaccess"),
    path('disapproveaccess1/<str:pk>/', views.disapproveaccess1, name="disapproveaccess1"),
    path('approveaccess1/<str:pk>/', views.approveaccess1, name="approveaccess1"),
    path('disapproveexamaccess1/<str:pk>/', views.disapproveexamaccess1, name="disapproveexamaccess1"),
    path('approveexamaccess1/<str:pk>/', views.approveexamaccess1, name="approveexamaccess1"),
    path('disapproveresultaccess/<str:pk>/', views.disapproveresultaccess, name="disapproveresultaccess"),
    path('approveresultaccess/<str:pk>/', views.approveresultaccess, name="approveresultaccess"),
    path('loginaccess/', views.loginaccess, name="loginaccess"),
    path('examaccess/', views.examaccess, name="examaccess"),
    path('loginaccess1/', views.loginaccess1, name="loginaccess1"),
    path('examaccess1/', views.examaccess1, name="examaccess1"),
    path('resultaccess/', views.resultaccess, name="resultaccess"),
    path('logout/', LogoutView.as_view(template_name= "dashboard/logout.html"),name='logout'),
    
    path('registerlecturer/', views.registerlecturer, name="registerlecturer"),
    path('viewfaculty/', views.viewfaculty, name="viewfaculty"),
    path('registeradmin/', views.registeradmin, name="registeradmin"),
    path('registerregistry/', views.registerregistry, name="registerregistry"),
    path('registerbursary/', views.registerbursary, name="registerbursary"),
    path('registerhod/', views.registerhod, name="registerhod"),
    path('registersupervisor/', views.registersupervisor, name="registersupervisor"),
    path('registerlibrary/', views.registerlibrary, name="registerlibrary"),
    path('registersuperadmin/', views.registersuperadmin, name="registersuperadmin"),
    
    
    path('allstudents/', views.allstudents, name="allstudents"),
    path('alllecturers/', views.alllecturers, name="alllecturers"),
    path('deletemark/<str:pk>/', views.deletemark, name="deletemark"),
    path('lecturerview/', views.lecturerview, name="lecturerview"),
    path('adminprofile/', views.adminprofile, name="adminprofile"),
    path('updatefaculty/<str:pk>/', views.updatefaculty, name="updatefaculty"),
    path('updatedepartment/<str:pk>/', views.updatedepartment, name="updatedepartment"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('viewresult/', views.viewresult, name="viewresult"),
    path('adminsturesult//<str:pk>/', views.adminsturesult, name="adminsturesult"),
    path('allresult/', views.allresult, name="allresult"),
    path('allexam/', views.allexam, name="allexam"),
    path('alllogin/', views.alllogin, name="alllogin"),
    path('allresult1/', views.allresult1, name="allresult1"),
    path('allexam1/', views.allexam1, name="allexam1"),
    path('alllogin1/', views.alllogin1, name="alllogin1"),
    path('resettab/', views.resettab, name="resettab"),
    path('resetexam/', views.resetexam, name="resetexam"),
    path('adminexamtable/', views.adminexamtable, name="adminexamtable"),
    path('admintable/', views.admintable, name="admintable"),
    path('payroll/', views.payroll, name="payroll"),
    path('staffpayroll/', views.staffpayroll, name="staffpayroll"),
    path('lecturerpayroll/', views.lecturerpayroll, name="lecturerpayroll"),
    path('lecpay/<str:pk>/', views.lecpay, name="lecpay"),
    path('addpayroll/', views.addpayroll, name="addpayroll"),
    path('status/', views.status, name="status"),
    path('viewstatus/', views.viewstatus, name="viewstatus"),
    path('attaccess/', views.attaccess, name="attaccess"),
    path('disatt/<str:pk>/', views.disatt, name="disatt"),
    path('appatt/<str:pk>/', views.appatt, name="appatt"),
    path('regcourse/<str:pk>/', views.regcourse, name="regcourse"),
    path('deleteresult/<str:pk>/', views.deleteresult, name="deleteresult"),
    path('deletestaffpayroll/<str:pk>', views.deletestaffpayroll, name="deletestaffpayroll"),
    path('addcalendar/', views.addcalendar, name="addcalendar"),
    path('resetcalendar/', views.resetcalendar, name="resetcalendar"),
    path('deletedepnotice/<str:pk>', views.deletedepnotice, name="deletedepnotice"),
    path('deletenotice/<str:pk>', views.deletenotice, name="deletenotice"),
    path('template2/', views.template2, name="template2"),
    path('template3/', views.template3, name="template3"),
    path('template4/', views.template4, name="template4"),
    path('template/', views.template, name="template"),
    path('stucourse/', views.stucourse, name="stucourse"),
    path('coursestudent/<str:pk>/', views.coursestudent, name="coursestudent"),
    path('deletestatus/', views.deletestatus, name="deletestatus"),
    path('viewmessage/', views.viewmessage, name="viewmessage"),
    path('template1/', views.template1, name="template1"),
    path('sentmessage/', views.sentmessage, name="sentmessage"),
    path('student/<str:pk_profile>/', views.student, name="student"),
    path('viewtransaction/<str:pk>/', views.viewtransaction, name="viewtransaction"),
    path('uploadfile/', views.uploadfile, name="uploadfile"),
    path('newnotice/', views.newnotice, name="newnotice"),
    path('newnotice1/', views.newnotice1, name="newnotice1"),
    path('noticeboard/', views.noticeboard, name="noticeboard"),
    path('debitpayment/', views.debitpayment, name="debitpayment"),
    path('creditpayment/', views.creditpayment, name="creditpayment"),
    path('resettable/', views.resettable, name="resettable"),
    path('receipt/<str:pk>/', views.receipt, name="receipt"),
    path('transactions', views.transactions, name="transactions"),
    path('summary/<str:pk>/', views.summary, name="summary"),
    path('generalnotice/', views.generalnotice, name="generalnotice"),
    path('departmentnotice/', views.departmentnotice, name="departmentnotice"),
    
    path('viewbook/', views.viewbook, name="viewbook"),
    path('studentlib/', views.studentlib, name="studentlib"),
    path('issuedlibook/', views.issuedlibook, name="issuedlibook"),
    path('attendance/', views.attendance, name="attendance"),
    path('examrecord/', views.examrecord, name="examrecord"),
    path('malpracticeview/', views.malpracticeview, name="malpracticeview"),
    path('deletemalpractice/<str:pk>/', views.deletemalpractice, name="deletemalpractice"),
    path('summary/', views.summary, name="summary"),
    path('lecturer/<str:pk_profile1>/', views.lecturer, name="lecturer"),
    path('updatelecturer/<str:pk1>/', views.updatelecturer, name="updatelecturer"),
    path('lectureresult/<str:pk>/', views.lectureresult, name="lectureresult"),
    
    path('updatestudent/<str:pk>/', views.updatestudent, name="updatestudent"),
    

    path('newcourse/', views.newcourse, name="newcourse"),
    path('viewcourse/<str:pk>/', views.viewcourse, name="viewcourse"),
    path('adminviewcourse/', views.adminviewcourse, name="adminviewcourse"),
    path('updatecourse/<str:pk>/', views.updatecourse, name="updatecourse"), 
    path('studentmark/', views.studentmark, name="studentmark"),
    path('marks/<str:pk>/', views.marks, name="marks"),
    path('checkmarks/<str:pk>/', views.checkmarks, name="checkmarks"),
    path('newstudentlevy/', views.newstudentlevy, name="newstudentlevy"),
    path('result/', views.result, name="result"),
    
    path('viewdepartment', views.viewdepartment,name='viewdepartment'),
    path('setexamtable', views.setexamtable,name='setexamtable'),
    path('settimetable', views.settimetable,name='settimetable'),
    path('addquestion', views.addquestion,name='addquestion'),
    path('viewquestion', views.viewquestion,name='viewquestion'),
    path('viewquestionview/<str:pk>', views.viewquestionview,name='viewquestionview'),
    path('deletequestion/<str:pk>', views.deletequestion,name='deletequestion'),

    path('newdepartment/', views.newdepartment, name="newdepartment"),
    path('newfaculty/', views.newfaculty, name="newfaculty"),
    path('faculty/<str:pk_profile2>/', views.faculty, name="faculty"),
    path('department/<str:pk_profile3>/', views.department, name="department"),
    path('deletemessage/<str:pk>/', views.deletemessage, name="deletemessage"),
	path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('img/favicon.ico'))),
 
    
    path('calendar/', views.CalendarView.as_view(),name='calendar'),
    
    
    path('changepassword/', views.changepassword, name="changepassword"),
    path('regstucourse/', views.regstucourse, name="regstucourse"),
    path('deletemessage/', views.deletemessage, name="deletemessage"),
    path('groupchange/<str:pk>/', views.groupchange, name="groupchange"),
    path('changegroup/', views.changegroup, name="changegroup"),
   
   
    path('reset_password/', 
         auth_views.PasswordResetView.as_view(template_name='Permissions/resetpassword.html'),name='reset_password'),
    
    path('password_reset_done/',
         auth_views.PasswordResetDoneView.as_view(template_name='Permissions/resetpasswordsent.html'),name='password_reset_done'),
    
    path('password_reset_confirm/<uidb64>/<token>/', 
         auth_views.PasswordResetConfirmView.as_view(template_name='Permissions/resetpasswordform.html'),name='password_reset_confirm'),
    
    path('password_reset_complete/', 
         auth_views.PasswordResetCompleteView.as_view(template_name='Permissions/resetpasswordconfirm.html'),name='password_reset_complete'),

    
]

