# Generated by Django 3.2.4 on 2022-10-24 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20221024_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='student',
        ),
    ]
