# Generated by Django 3.2.4 on 2022-10-29 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0009_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Malpractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('supervisor', models.CharField(blank=True, max_length=30, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.course')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.student')),
            ],
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_student', models.IntegerField(blank=True, default=0, null=True)),
                ('present_student', models.IntegerField(blank=True, default=0, null=True)),
                ('absence_student', models.IntegerField(blank=True, default=0, null=True)),
                ('co_supervisor1', models.CharField(blank=True, max_length=30, null=True)),
                ('co_supervisor2', models.CharField(blank=True, max_length=30, null=True)),
                ('co_supervisor3', models.CharField(blank=True, max_length=30, null=True)),
                ('co_supervisor4', models.CharField(blank=True, max_length=30, null=True)),
                ('co_supervisor5', models.CharField(blank=True, max_length=30, null=True)),
                ('time_start', models.TimeField(blank=True, null=True)),
                ('time_end', models.TimeField(blank=True, null=True)),
                ('supervisor', models.CharField(blank=True, max_length=30, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.course')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.department')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='ExamAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor', models.CharField(blank=True, max_length=30, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.course')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.student')),
            ],
        ),
    ]
