# Generated by Django 3.2.4 on 2022-10-29 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examination',
            name='absence_student',
        ),
        migrations.RemoveField(
            model_name='examination',
            name='co_supervisor1',
        ),
        migrations.RemoveField(
            model_name='examination',
            name='co_supervisor2',
        ),
        migrations.RemoveField(
            model_name='examination',
            name='co_supervisor3',
        ),
        migrations.RemoveField(
            model_name='examination',
            name='co_supervisor4',
        ),
        migrations.RemoveField(
            model_name='examination',
            name='co_supervisor5',
        ),
        migrations.RemoveField(
            model_name='examination',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='examination',
            name='present_student',
        ),
        migrations.RemoveField(
            model_name='examination',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='examination',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='examination',
            name='time_start',
        ),
        migrations.RemoveField(
            model_name='examination',
            name='total_student',
        ),
    ]
