# Generated by Django 3.2.4 on 2022-10-29 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0012_auto_20221029_0915'),
        ('supervisor', '0002_auto_20221029_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='absence_student',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='examination',
            name='co_supervisor1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='examination',
            name='co_supervisor2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='examination',
            name='co_supervisor3',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='examination',
            name='co_supervisor4',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='examination',
            name='co_supervisor5',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='examination',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.faculty'),
        ),
        migrations.AddField(
            model_name='examination',
            name='present_student',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='examination',
            name='supervisor',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='examination',
            name='time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examination',
            name='time_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examination',
            name='total_student',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
