# Generated by Django 4.1.3 on 2022-11-03 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0003_auto_20221029_1047'),
    ]

    
