# Generated by Django 4.1.3 on 2022-11-06 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0004_delete_examattendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='malpractice',
            name='course',
        ),
        migrations.RemoveField(
            model_name='malpractice',
            name='student',
        ),
        migrations.DeleteModel(
            name='Examination',
        ),
        migrations.DeleteModel(
            name='Malpractice',
        ),
    ]
