# Generated by Django 4.1.3 on 2022-11-06 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamAttendance',
        ),
    ]
