# Generated by Django 4.1.3 on 2022-11-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0008_remove_examination_co_supervisor5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='malpractice',
            name='action',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
